ithacaxyz/account

- deployments.md
- script/DeployDelegation.s.sol
- script/DeployDelegationImplementation.s.sol
- script/DeployEntryPoint.s.sol
- script/DeployEntryPointImplementation.s.sol
- src/Delegation.sol
> Combined updates 2

- script/UpgradeDelegation.s.sol
- src/Delegation.sol
Anything that deals with delegatecall is a can of worms.
> Delegatecall mode fix and redeploy

- .gitmodules
- deployments.md
- script/DeployDelegation.s.sol
https://odyssey-explorer.ithaca.xyz/address/0x839569e0ab2a9CCd648f350Cde00958D81d1F729
> New Delegation Proxy

- .gitmodules
- src/Delegation.sol
Redeployments in a separate PR later.
> ♻️ New EIP-7702 proxy

- src/EntryPoint.sol
- test/EntryPoint.t.sol
@atarpara For any test that is named with "Gas", don't fuzz.
> Minor optimizations and tidy tests

- .gitmodules
- src/EntryPoint.sol
> Optimize EntryPoint fill

- src/EntryPoint.sol
> Fix _execute revert

- src/EntryPoint.sol
0x1f - > 0x20
I shouldn't code when I'm not alert.
> Fix _execute revert 2

- .github/workflows/ci.yaml
add simple workflow running tests for accounts contracts
> Add basic workflow on the accounts contracts

- src/GuardedExecutor.sol
- test/GuardedExecutor.t.sol
> Fix removeSpendLimit and add test

- src/GuardedExecutor.sol
> Remove daily in GuardedExecutor comments

- .github/workflows/deploy.yaml
seems that you can't add comments to `run` body like this
> fix: move comment

- .changeset/long-schools-ring.md
- .changeset/silly-walls-speak.md
- .changeset/some-coats-beam.md
- CHANGELOG.md
- deployments.md
- package.json
- src/Delegation.sol
- src/EntryPoint.sol
- src/GuardedExecutor.sol
- test/GuardedExecutor.t.sol
More descriptive error.
This might be a breaking change.
> feat: add UnauthorizedCall error to GuardedExecutor

- .changeset/fluffy-windows-stop.md
- .changeset/slick-foxes-mix.md
- package.json
- src/Delegation.sol
- src/DeployAll.sol
- src/EntryPoint.sol
- test/Base.t.sol
- test/EntryPoint.t.sol
- test/LibNonce.t.sol
- test/utils/mocks/MockEntryPoint.sol
> Add back PreOps and Delegation Implementation PRs

- test/GuardedExecutor.t.sol
Fixes a broken test on main, related to guarded executor.
> test: fix guarded executor test

- src/Delegation.sol
- test/Delegation.t.sol
- test/utils/mocks/MockSampleDelegateCallTarget.sol
Marinating if this is generalized enough and also secure.
This is non-breaking, as of now.
> feat: upgradeHook

- .github/workflows/deploy.yaml
add --private-key flag on deploy
triggered deployment for testing: https://github.com/ithacaxyz/account/actions/runs/15113491815/job/42478241194
> Fix ci deployment

- test/Account.t.sol
This PR adds unit tests for two critical Ithaca account features:
1. Cross-chain key synchronization using PreCalls with multichain nonces (testCrossChainKeyAuthorization)
2. Paymaster flow with Intent-based (testPaymasterPay)
> Added test for new Flows

- src/GuardedExecutor.sol
- src/MultiSigSigner.sol
- src/PauseAuthority.sol
- src/SimpleFunder.sol
> Edit comments

- CLAUDE.md
Claude often writes things logically step by step, when they should be written using CEI instead. This sometimes adds hard to catch vulns related to reentrancy.
> chore: add reentrancy knowledge to claude md

- deploy/FundSimpleFunder.s.sol
This PR adds a new script to easily fund SimpleFunder contracts with native and ERC20 tokens across multiple chains.
**1. Set up your environment variables:**
```bash
export PRIVATE_KEY=0x...  # Your private key with funds
export RPC_84532=https://base-sepolia.g.alchemy.com/v2/YOUR_KEY  # Base Sepolia
export RPC_11155420=https://opt-sepolia.g.alchemy.com/v2/YOUR_KEY  # OP Sepolia
```
**2. Run the script:**
**Example: Send native tokens (ETH) to SimpleFunder**
```bash
forge script deploy/FundSimpleFunder.s.sol:FundSimpleFunder \
--sig "run(address,(uint256,address,uint256)[])" \
0xYourSimpleFunderAddress \
"[(84532,0x0000000000000000000000000000000000000000,1000000000000000000)]" \
--broadcast --multi --slow --private-key $PRIVATE_KEY
```
**Example: Send ERC20 tokens**
```bash
forge script …
```
> feat: add script to fund the simple funder

- src/IthacaAccount.sol
- src/Orchestrator.sol
- test/Account.t.sol
add a simple replay safe wrapper
> fix: 1271 replay issue

- .gitmodules
- foundry.lock
- remappings.txt
- src/vendor/layerzero/mocks/EndpointV2Mock.sol
- test/LayerZeroSettler.t.sol
The devtools repo takes too long to load, this PR removes it as a dependencies, and copy pastes the relevant code into the file.
> chore: remove devtools dependency
