src/Delegation.sol
src/EntryPoint.sol
src/GuardedExecutor.sol

- ERC20 and native token spend permissions.
Todo:
- Write tests.
- EntryPoint create2 address.
- Ability to let delegation approve more than one EntryPoint (tied to current delegation codehash). This allows for the delegation to possibly switch to a more performant, but abi equivalent EntryPoint in the future.
Thoughts:
- The EntryPoint is quite a complex beast, due to it's need for gas introspection and performance, just like the 4337 EntryPoint. I think in the end state, a good EntryPoint will be written in very optimized inline-assembly. Also, the main bottleneck in Base's gas costs by far is L2 gas.

Draft updates 2

---

src/GuardedExecutor.sol

Inside the inner `for` loop, the variable `i` was mistakenly used instead of `j` to access elements of the `periods` array. 
This caused incorrect behavior since `i` is already used in the outer loop.  
Changes made:  
- Replaced `periods[i]` with `periods[j]` to ensure proper access to the array elements.

fix: Fix incorrect variable usage in inner loop

---

script/UpgradeDelegation.s.sol
script/UpgradeEntryPoint.s.sol
src/Delegation.sol
src/EntryPoint.sol
src/GuardedExecutor.sol

Tidy and optimize

---

src/Delegation.sol
src/EntryPoint.sol
test/EntryPoint.t.sol

Rationale:
Right now, the EntryPoint nonce system is in the Delegation. This means that when a transaction fails, the ERC20 payment is actually made, but the nonce isn't consumed. This is dangerous, since the signed userop can be abused to drain the ERC20 of the eoa.
This PR does 3 things.
1. Move the EntryPoint nonce system to the EntryPoint itself. This means if a UserOp fails, the nonce will still be consumed.
2. Change the nonce style to be a 4337-style 2D nonce [more info](https://hackmd.io/@atarpara/BkU-NNz5yl). 
- Previously, we can invalidate all the unused signatures by simply incrementing `nonceSalt`. This 2D nonce system does not have `nonceSalt`. This means to invalidate all the unused signatures, one must take note of all the `keySeq` (i.e. the upper 192 bits that have been …

♻️ Refactor EntryPoint nonces

---

script/UpgradeEntryPoint.s.sol

This previously left the entrypoint proxy in a non-upgradeable state which broke my entrypoint deployment

fix: call `_initializeOwnerData()` on entrypoint upgrade

---

src/EntryPoint.sol

Makes upgrading easier.
Previously, I removed the call to `_initializeOwner()`, which broke the upgrade script.
This allows the script to initialize the owner if one doesn't exist.

Change initialize owner to conditional

---

src/Delegation.sol
src/EntryPoint.sol

This will allow the optimization for the case where `paymentPerGas == 0` or `paymentPerGas == type(uint256).max`.
For this special case, we can directly pay the desired recipient and skip the entire refund workflow.
I think in the end game, where there is sufficient incentives for relayers to pay exact gas, this optimization can become favorable.
This should not be a breaking change unless you need to access the specific ERC20 transfer events.

Refactor payEntryPoint to compensate

---

src/EntryPoint.sol
test/EntryPoint.t.sol

Make the estimate much tighter by heuristically determining if we are verifying P256 without a precompile.

Improve simulateExecution2 even more

---

src/EntryPoint.sol

The reason i didn’t bubble up the whole error by default, and replace it with a generic `CallError` was that it’s to prevent someone from griefing the EntryPoint by making the returndata some crazy big amount.
But i realized that if it’s just a regular 4-byte error, we can safely bubble it up.

Make EntryPoint actually bubble up the error if it is small

---

src/EntryPoint.sol
test/EntryPoint.t.sol

So that we don't need to go thru all those signature guessing stuff.
This PR still simulates the gas burn from the signature validation, but it avoids reverting if the signature is invalid. This allows the relay to simulate the guarded executor overhead for the particular `keyHash`, without needing a proper signature from that `keyHash`.

Verification agnostic gas estimation

---

src/EntryPoint.sol
test/Base.t.sol
test/EntryPoint.t.sol
test/SimulateExecute.t.sol

This will be breaking.
- The reverted error's has changed to `error SimulationResult(uint256 gExecute, uint256 gCombined, uint256 gUsed, bytes4 err)`.
- The function has changed to `simulateExecute(bytes encodedUserOp)`.

Refactor simulate execute names

---

src/GuardedExecutor.sol
test/GuardedExecutor.t.sol

This should be non-breaking, unless you require very specific behavior of GuardedExecutor to only apply the spend limits after a batch.

Add intra batch spend limit detection for GuardedExecutor

---

src/Delegation.sol
src/GuardedExecutor.sol
test/GuardedExecutor.t.sol

When a `keyHash` is revoked and readded, we want all its GuardedExecutor state to be reset.
While it is unlikely that a will be revoked and readded, we want to still allow for this possibility, but allow it to be performed in a safe way.
This is implemented by using the `extraKeyStorage` slot as a seed to get the storage slot for the GuardedExecutor variables.

Make GuardedExecutor reset storage upon keyHash revoke

---

src/EntryPoint.sol

This comment references `nonceStatus` which no longer exists.

docs: rm ref to `nonceStatus`

---

src/GuardedExecutor.sol

To be used only on `eth_call` to fetch all spend and execute permissions from a set of keys.

feat: add `spendAndExecuteInfos` to `Delegation` contract

---

src/AccountRegistry.sol
src/EntryPoint.sol

Adds `AccountRegistry` with 3 methods:
- `register` - to initialize a mapping for the given ID with an account and arbitrary data blob.
- `appendAccount` - to add a new account to the ID.
- `idInfo` to fetch the data blob and a list of accounts.

feat: `AccountRegistry`

---

.github/workflows/deploy.yaml

Blockscout does not accept `prague` EVM version by default. This should be fixed with https://github.com/blockscout/blockscout/pull/12115. For now this PR sets the `evm_version` to `cancun` as `prague` is basically the same thing from solc pov
Closes https://github.com/ithacaxyz/account/issues/84

feat: verify contracts in deploy workflow

---

.changeset/new-shirts-film.md
src/Delegation.sol
src/EntryPoint.sol
test/GuardedExecutor.t.sol
test/utils/mocks/MockPayerWithSignature.sol
test/utils/mocks/MockPayerWithState.sol

Continued from 105.
- The `compensate` function has been refactored to take in an additional `keyHash` parameter.

fix: compensate spend limits

---

src/EntryPoint.sol
test/utils/mocks/MockEntryPoint.sol

I've defined constants as flags, to be more descriptive. The previous trick of abusing `bytes32("gVerify")` can mess things up if you want to add more flags in the future.

feat: simulation full bubble revert

---

.changeset/tangy-suns-study.md
src/EntryPoint.sol
test/SimulateExecute.t.sol

So, when `err == PaymentError.selector`, `gCombined` will be left as default 0 -> `paymentOverride = 0` -> final simulation won't revert. 
So the fix is to directly revert if `err == PaymentError.selector`, for the no-revert `simulateExecute` workflow.

fix: make simulateExecute directly revert on PaymentError

---

.github/workflows/ci.yaml
package.json

Fetches the latest gas snapshot from main branch, and diffs them against the current PR.
Helps to make sure that new PRs don't regress on old benchmarks.
Right now, the diffs are only visible in the CI run. We could consider posting them as a comment on the PR itself, but this requires adding a github token in the secrets.
Thoughts?

Automating gas benchmark diffs with main in CI

---

src/Simulator.sol

We do this to cover edge cases in paymaster flows, where a small change in the payment amount can cause big codepath changes, causing simulation to fail.

chore: update payment in combinedGas loop

---

script/DeployAll.s.sol
src/Delegation.sol
src/EntryPoint.sol
test/EntryPoint.t.sol

Allows delegation to be the paymaster.
@relay Note that after this PR, if you explicitly set the payer field to the EOA itself for normal flows, then it will give an error, because it will consider the EOA to be a paymaster.
For non-paymaster flows, u.payer should just be left empty.

feat: Allow Porto Delegation accounts to act as Paymasters

---

script/DeployAll.s.sol

PR removes PK env variable from deploy all 
Tested: deploy ci still works bc it is setting the deployer key already https://github.com/ithacaxyz/account/actions/runs/15026063535

Remove PK env from deploy script

---

.gitmodules
src/GuardedExecutor.sol
test/GuardedExecutor.t.sol

**Use case:**
App asks user to authorize some session key that is authorize to pull a fixed amount of assets _only once_. 
The pulled assets could then go into some sub account where some bot could run automated trading on.
**Note:**
Due to the whitelist nature of our spend limits, a trading bot cannot work directly on the EOA using a P256 key. Say if it has swapped 1000 USDC to some memecoin, a separate spend permission has to be granted by a superAdmin to swap that memecoin out to sell. Granting superAdmins is a very risky move. The way around this is sub accounts.

feat: forever period to GuardedExecutor

---

src/Simulator.sol
test/SimulateExecute.t.sol

In the combinedGas loop, the payment is also incremented along with the combined gas.
There might come a point, where the user does not have enough funds for the payment. The user cannot recover from this, so we revert in the loop.

Catch Payment Errors in Simulate Loop

---

test/Base.t.sol

Fixes https://github.com/ithacaxyz/account/issues/150
I was browsing through the repo and got nerd-sniped to look into this. The function that returns the delegation and implementation is implemented with Solady's `LibEIP7702.delegationAndImplementationOf();`:
https://github.com/ithacaxyz/account/blob/210ca4bf53aa7e26224edf2b36365a390fc4bdd6/src/EntryPoint.sol#L635-L641
which internally verifies the hash of the runtime bytecode of the proxy:
https://github.com/vectorized/solady/blob/d7469ddff36d90beac6587ddb5128337c14e7df6/src/accounts/LibEIP7702.sol#L99-L112
and the proxy itself is deployed in `Base.t.sol` with the `new` keyword, which means that the bytecode that gets deployed is affected by the project's compiler settings:
https://github.com/ithacaxyz/account/blob/210ca4bf53aa7e26224edf …

Fix delegationImplementationOf test with optimizer turned off + fix forge coverage

---

test/Base.t.sol
test/Benchmark.t.sol
test/Delegation.t.sol

A follow-up to https://github.com/ithacaxyz/account/pull/162 to prevent similar issues when switching compiler settings

Refactor EIP7702Proxy instantiation to use LibEIP7702 for proxy deployment in tests

---

CHANGELOG.md
src/Delegation.sol
src/MultiSigSigner.sol
src/interfaces/IDelegation.sol
src/interfaces/ISigner.sol
src/libraries/LibMultiSig.sol
src/libraries/LibTStack.sol
test/Base.t.sol
test/EntryPoint.t.sol
test/LibTStack.t.sol

- Adds support for `External` keytype. Which allows external contracts that implement the `ISigner` 
to verify signatures. 
- Adds a `MultiSigSigner` which adds multi-sig support to the account, using `External` keytype.#151 
- Adds a stack of `context key hashes` to the account. External observers can check which key signed
the account's current execution, by calling the `getContextKeyHash` function on the msg.sender.
This has a variety of usecases like validating key operations, setting data in account registry etc.
This mechanism can also be used to solve #154 
- Only adds features. Should not have breaking changes for @relay.

Add External key type + multi sig

---

.github/workflows/claude-code.yml
.github/workflows/claude-review.yml

Modified the Claude PR review workflow to only trigger when the 'claude-review' label is added to a PR, rather than running automatically on every PR opened or marked ready for review. (This was spamming our open PRs)
This gives maintainers more control over when Claude reviews are performed and reduces unnecessary workflow runs.
The @claude mention functionality in issues and PR comments was already implemented in the claude-code.yml workflow, but wasn't working for some reason. We will only be able to test it, once this gets merged to main.

refactor: configure Claude CI/CD for label-triggered PR reviews

---

src/libraries/LibTStack.sol

Declare error EmptyStack(); at file scope in src/libraries/LibTStack.sol
Keeps existing assembly reverts (selector 0xbc7ec779) — no behavior change
Improves readability and enables tooling/decoders to resolve the revert
Affects top and pop paths only

refactor(LibTStack): declare EmptyStack error for proper revert decoding

---

CHANGELOG.md
deploy/DeployMain.s.sol
deploy/FundSigners.s.sol
deploy/README.md
deploy/config.toml
package.json
script/DeployAll.s.sol
src/SimpleFunder.sol
src/interfaces/IFunder.sol
test/Orchestrator.t.sol
test/SimpleFunder.t.sol

SimpleFunder now supports multiple orchestrators instead of a single immutable
orchestrator. The `ORCHESTRATOR` immutable field has been replaced with an
`orchestrators` mapping that can be managed by the contract owner.
Deployment scripts updated to configure orchestrators after SimpleFunder deployment
using the new `supported_orchestrators` config field.
@kuyziss @jenpaff @laibe There is an additional config variable in the FundSigners script, which you have to set with all orchestrators, including the latest deployments.
This step has to be completed before running anything interop related.

feat: allow funders to support older ocs

---

test/MultiSigSigner.t.sol
test/utils/mocks/MockAccount.sol

We had a big multi sig test in Orchestrator before this, but it is also valuable to have a separate testing suite for the MultiSigSigner just for completeness and sanity.

test: add comprehensive MultiSigSigner tests
